"""Generate the official-source catalog from canonical YAML."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml


@dataclass(frozen=True, slots=True)
class CheckResult:
    exit_code: int
    message: str


def _load_list(path: Path, key: str) -> list[dict[str, Any]]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or not isinstance(data.get(key), list):
        raise ValueError(f"{path}: expected top-level {key} list")
    return [item for item in data[key] if isinstance(item, dict)]


def _display(value: object) -> str:
    if value is None:
        return "-"
    if isinstance(value, bool):
        return "yes" if value else "no"
    return str(value).replace("|", "\\|")


def _instrument_ids(source: dict[str, Any]) -> tuple[str, ...]:
    declared: list[str] = []
    single = source.get("instrument_id")
    if isinstance(single, str):
        declared.append(single)
    multiple = source.get("instrument_ids")
    if isinstance(multiple, list):
        declared.extend(item for item in multiple if isinstance(item, str))
    return tuple(dict.fromkeys(declared))


def render_registry(registry_path: Path, instruments_path: Path) -> str:
    """Render one stable Markdown catalog grouped by authority."""

    sources = _load_list(registry_path, "sources")
    instruments = _load_list(instruments_path, "instruments")
    statuses = {
        item.get("id"): item.get("status")
        for item in instruments
        if isinstance(item.get("id"), str)
    }
    grouped: dict[str, list[dict[str, Any]]] = {}
    for source in sources:
        grouped.setdefault(str(source.get("authority", "Unknown")), []).append(source)

    lines = [
        "# Generated official-source registry",
        "",
        "<!-- Generated by python -m scripts.build_catalog. Do not edit manually. -->",
        "",
        "Transport availability is not a legal-status decision. Publication events are retained for temporal queries, and consolidated texts are identified separately.",
        "",
    ]
    for authority in sorted(grouped, key=str.casefold):
        lines.extend(
            [
                f"## {authority}",
                "",
                "| Source | Jurisdiction | Evidence | Instrument / status | Harvest | Cadence | Published | Official URL |",
                "|---|---|---|---|---:|---:|---|---|",
            ]
        )
        for source in sorted(
            grouped[authority],
            key=lambda item: (
                str(item.get("jurisdiction", "")),
                str(item.get("title", "")).casefold(),
                str(item.get("id", "")),
            ),
        ):
            instrument_parts = []
            for instrument_id in _instrument_ids(source):
                instrument = _display(instrument_id)
                if instrument_id in statuses:
                    instrument = f"{instrument_id} / {statuses[instrument_id]}"
                instrument_parts.append(instrument)
            instrument_display = "<br>".join(instrument_parts) if instrument_parts else "-"
            title = _display(source.get("title"))
            source_id = _display(source.get("id"))
            url = _display(source.get("url"))
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{source_id}`<br>{title}",
                        _display(source.get("jurisdiction")),
                        _display(source.get("evidence_class")),
                        instrument_display,
                        _display(source.get("harvest")),
                        _display(source.get("cadence_days")),
                        _display(source.get("publication_date")),
                        f"[open]({url})",
                    ]
                )
                + " |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def run_check(root: Path) -> CheckResult:
    expected = render_registry(
        root / "sources" / "registry.yaml", root / "sources" / "instruments.yaml"
    )
    output = root / "docs" / "catalog" / "registry.md"
    try:
        actual = output.read_text(encoding="utf-8")
    except OSError:
        actual = ""
    if actual != expected:
        return CheckResult(
            1,
            "generated catalog is stale; regenerate with: python -m scripts.build_catalog",
        )
    return CheckResult(0, "generated catalog is current")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", nargs="?", type=Path, default=Path.cwd())
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    if args.check:
        result = run_check(args.root)
        print(result.message)
        return result.exit_code
    output = args.root / "docs" / "catalog" / "registry.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        render_registry(
            args.root / "sources" / "registry.yaml",
            args.root / "sources" / "instruments.yaml",
        ),
        encoding="utf-8",
    )
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
