"""Generate deterministic official-source catalog pages from canonical YAML."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from scripts.archive_metadata import archive_label


@dataclass(frozen=True, slots=True)
class CheckResult:
    exit_code: int
    message: str


def _load_list(path: Path, key: str) -> list[dict[str, Any]]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or not isinstance(data.get(key), list):
        raise ValueError(f"{path}: expected top-level {key} list")
    return [item for item in data[key] if isinstance(item, dict)]


def _display(value: object) -> str:
    if value is None:
        return "-"
    if isinstance(value, bool):
        return "yes" if value else "no"
    return str(value).replace("|", "\\|")


def _instrument_ids(source: dict[str, Any]) -> tuple[str, ...]:
    declared: list[str] = []
    single = source.get("instrument_id")
    if isinstance(single, str):
        declared.append(single)
    multiple = source.get("instrument_ids")
    if isinstance(multiple, list):
        declared.extend(item for item in multiple if isinstance(item, str))
    return tuple(dict.fromkeys(declared))


def _instrument_statuses(instruments_path: Path) -> dict[str, object]:
    return {
        item.get("id"): item.get("status")
        for item in _load_list(instruments_path, "instruments")
        if isinstance(item.get("id"), str)
    }


def _instrument_display(source: dict[str, Any], statuses: dict[str, object]) -> str:
    parts: list[str] = []
    for instrument_id in _instrument_ids(source):
        instrument = _display(instrument_id)
        if instrument_id in statuses:
            instrument = f"{instrument_id} / {statuses[instrument_id]}"
        parts.append(instrument)
    return "<br>".join(parts) if parts else "-"


def render_registry(registry_path: Path, instruments_path: Path) -> str:
    """Render one stable Markdown catalog grouped by authority."""

    sources = _load_list(registry_path, "sources")
    statuses = _instrument_statuses(instruments_path)
    grouped: dict[str, list[dict[str, Any]]] = {}
    for source in sources:
        grouped.setdefault(str(source.get("authority", "Unknown")), []).append(source)

    lines = [
        "# Generated official-source registry",
        "",
        "<!-- Generated by python -m scripts.build_catalog. Do not edit manually. -->",
        "",
        "Transport availability is not a legal-status decision. Publication events are retained for temporal queries, and consolidated texts are identified separately.",
        "",
    ]
    for authority in sorted(grouped, key=str.casefold):
        lines.extend(
            [
                f"## {authority}",
                "",
                "| Source | Jurisdiction | Evidence | Instrument / status | Harvest | Cadence | Published | Official URL |",
                "|---|---|---|---|---:|---:|---|---|",
            ]
        )
        for source in sorted(
            grouped[authority],
            key=lambda item: (
                str(item.get("jurisdiction", "")),
                str(item.get("title", "")).casefold(),
                str(item.get("id", "")),
            ),
        ):
            title = _display(source.get("title"))
            source_id = _display(source.get("id"))
            url = _display(source.get("url"))
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{source_id}`<br>{title}",
                        _display(source.get("jurisdiction")),
                        _display(source.get("evidence_class")),
                        _instrument_display(source, statuses),
                        _display(source.get("harvest")),
                        _display(source.get("cadence_days")),
                        _display(source.get("publication_date")),
                        f"[open]({url})",
                    ]
                )
                + " |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _archive_location(source: dict[str, Any]) -> str:
    archive = source.get("archive")
    if not isinstance(archive, dict):
        return "-"
    status = archive_label(source)
    if status == "local_git":
        return f"`{_display(archive.get('path'))}`"
    if status == "release_asset":
        return f"{_display(archive.get('release_tag'))} / {_display(archive.get('asset_name'))}"
    if status == "external_only":
        return _display(archive.get("reason"))
    return "-"


def _render_archive_section(
    title: str,
    sources: list[dict[str, Any]],
    statuses: dict[str, object],
) -> list[str]:
    lines = [f"## {title}", ""]
    if not sources:
        lines.extend(["No sources are classified in this archive state yet.", ""])
        return lines

    lines.extend(
        [
            "| Source | Authority | Published | Instrument / status | Archive location | SHA256 | Captured | Official URL |",
            "|---|---|---|---|---|---|---|---|",
        ]
    )
    for source in sorted(
        sources,
        key=lambda item: (
            str(item.get("authority", "")).casefold(),
            str(item.get("title", "")).casefold(),
            str(item.get("id", "")),
        ),
    ):
        archive = source.get("archive") if isinstance(source.get("archive"), dict) else {}
        source_id = _display(source.get("id"))
        title_text = _display(source.get("title"))
        url = _display(source.get("url"))
        sha256 = _display(archive.get("sha256"))
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{source_id}`<br>{title_text}",
                    _display(source.get("authority")),
                    _display(source.get("publication_date")),
                    _instrument_display(source, statuses),
                    _archive_location(source),
                    f"`{sha256}`" if sha256 != "-" else "-",
                    _display(archive.get("captured_at")),
                    f"[official]({url})",
                ]
            )
            + " |"
        )
    lines.append("")
    return lines


def render_library(registry_path: Path, instruments_path: Path) -> str:
    """Render the human-facing archive library from source metadata."""

    sources = _load_list(registry_path, "sources")
    statuses = _instrument_statuses(instruments_path)
    grouped = {
        status: [source for source in sources if archive_label(source) == status]
        for status in ("local_git", "release_asset", "external_only", "unclassified")
    }

    lines = [
        "# Official document library",
        "",
        "<!-- Generated by python -m scripts.build_catalog. Do not edit manually. -->",
        "",
        "This library records how official sources are preserved for reproducibility and auditability. Archive presence is evidence preservation only; it does not determine legal validity or currentness.",
        "",
        "Large originals may be stored as GitHub Release assets. Interactive or redundant sources may remain external-only when the reason is documented.",
        "",
    ]
    sections = (
        ("Local Git originals", "local_git"),
        ("GitHub Release assets", "release_asset"),
        ("External-only references", "external_only"),
        ("Unclassified sources", "unclassified"),
    )
    for title, status in sections:
        lines.extend(_render_archive_section(title, grouped[status], statuses))
    return "\n".join(lines).rstrip() + "\n"


def _expected_outputs(root: Path) -> dict[Path, str]:
    registry_path = root / "sources" / "registry.yaml"
    instruments_path = root / "sources" / "instruments.yaml"
    return {
        root / "docs" / "catalog" / "registry.md": render_registry(
            registry_path, instruments_path
        ),
        root / "docs" / "catalog" / "library.md": render_library(
            registry_path, instruments_path
        ),
    }


def run_check(root: Path) -> CheckResult:
    stale: list[str] = []
    for output, expected in _expected_outputs(root).items():
        try:
            actual = output.read_text(encoding="utf-8")
        except OSError:
            actual = ""
        if actual != expected:
            stale.append(output.name)
    if stale:
        return CheckResult(
            1,
            "generated catalog is stale for "
            + ", ".join(stale)
            + "; regenerate with: python -m scripts.build_catalog",
        )
    return CheckResult(0, "generated catalog is current")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", nargs="?", type=Path, default=Path.cwd())
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    if args.check:
        result = run_check(args.root)
        print(result.message)
        return result.exit_code

    for output, content in _expected_outputs(args.root).items():
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content, encoding="utf-8")
        print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
